### ISSUE TITLE
ROBOT reduce does not reduce subclasses between names by default

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#956]
Currently:

```
robot reduce -i o.ofn  -o reduced.ofn
```

Does not reduce A = B, A Sub B , B Sub A to A = B (where A and B are names).

Only this does:
```
robot reduce -i o.ofn --named-classes-only true -o reduced.ofn
```

@cmungall if this is intended, we should clarify this in the docs

**Comment by cmungall** [comment]
The docs are indeed confusing here:

_Reciprocal subclass axioms (e.g. A SubClassOf B, B SubClassOf A), entailing equivalence between A and B, may be removed by reduce. In this case it is important to assert an equivalence axiom (A EquivalentTo B) using the reason command before running reduce._

The "may" here is not helpful, as is the asymmetry between the two algorithms (NC only vs anonymous).

Leave this assigned to me and I will fix. There are some java docstrings that could be elevated up to the markdown.

Note there is a more detailed treatment of redundancy/transitive reduction here: https://github.com/balhoff/relation-graph/issues/63

**Comment by cmungall** [comment]
I think this is resolved now?

**Comment by matentzn** [comment]
I am not sure at all! I have not fixed this issue if it existed!
